const actionTypes = {
	INITIATE_LOGIN: 'INITIATE_LOGIN',
	LOGIN_ERROR: 'LOGIN_ERROR',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	INITIATE_LOGOUT: 'INITIATE_LOGOUT',
	USER_REAUTH: 'USER_REAUTH',
	USER_REAUTH_ERROR: 'USER_REAUTH_ERROR',
	USER_REAUTH_SUCCESS: 'USER_REAUTH_SUCCESS',
	LOAD_USER_CARD: 'LOAD_USER_CARD',
	LOAD_USER_ADDRESS: 'LOAD_USER_ADDRESS',
	LOGOUT_ERROR: 'LOGOUT_ERROR',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

	INITIATE_SIGNUP: 'INITIATE_SIGNUP',
	SIGNUP_ERROR: 'SIGNUP_ERROR',
	SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
};

export default actionTypes;